import {Spot} from "./Spot";

export interface SpotList {
    erangel: Spot[];
    miramar: Spot[];
}


export const BuiltInList: SpotList = {
    erangel: [
        {name: "School"},
        {name: "Plane Crash"},
        {name: "Zharki"},
        {name: "Georgopol"},
        {name: "例の５軒（６軒）"},
        {name: "ホスピタル"},
        {name: "Severny"},
        {name: "Shooting Range"},
        {name: "北東道沿い"},
        {name: "Stalber"},
        {name: ":pray: か　め　し　き :pray:"},
        {name: "Yasnaya集落"},
        {name: "Yasnaya Polyana"},
        {name: "マンション"},
        {name: "Lipovka"},
        {name: "Prison"},
        {name: "Yasnaya南西"},
        {name: "School"},
        {name: "Schoolマンション"},
        {name: "Rozhok"},
        {name: "水没"},
        {name: "Ruins"},
        {name: "Gatka"},
        {name: "Swamp Town"},
        {name: "うまあじポジ"},
        {name: "Quarry"},
        {name: "Quarry西海岸"},
        {name: "ハの字"},
        {name: "ぼつぼつ"},
        {name: "ファーム"},
        {name: "ファーム西"},
        {name: "テラス"},
        {name: "バンカー"},
        {name: "材木置き場"},
        {name: "ミルタ"},
        {name: "ミルタパワー"},
        {name: "ミリベ"},
        {name: "Novorepnoye"},
        {name: "ミリベ北どっか"},
        {name: "ミリベ南西"},
        {name: "フェリー埠頭"},
        {name: "Primosk"}
    ],
    miramar: [
        {name: "Ruins（北西）"},
        {name: "TrailerPark"},
        {name: "La Cobreria"},
        {name: "Crater Fields"},
        {name: "Water Treatment"},
        {name: "Torre Ahumada"},
        {name: "Campo Militar"},
        {name: "Tierra Bronca"},
        {name: "Cruz Del Valle"},
        {name: "El Azahar"},
        {name: "San Martin"},
        {name: "El Pozo"},
        {name: "Monte Nuevo"},
        {name: "Power Grid"},
        {name: "Pecado"},
        {name: "Graveyard"},
        {name: "Minas Generales"},
        {name: "Junkyard"},
        {name: "La Bendita"},
        {name: "Impala"},
        {name: ":skull: Impala東 :skull:"},
        {name: "Puerto Paraiso"},
        {name: "Los Leones"},
        {name: "Mines"},
        {name: "Chumacera"},
        {name: "Minas Del Valle"},
        {name: "Valle Del Mar"},
        {name: "Minas Del Sur"},
        {name: "Prison"},
        {name: "Los Higos"},
        {name: "Mines南ジプシー"}
    ]
};